@startuml
skinparam linetype ortho
skinparam classAttributeIconSize 0
top to bottom direction
'left to right direction




	together {
			!include jot.puml!Exercise
			!include jot.puml!SETS
			abstract class WorkoutSession <<abstract>> {
				+ SessionId: UUID
		        + **userId: UUID
		        + **sourceRoutineId: UUID?

		        + date: Date?
		        + startTime: Time?
		        + endTime: Time?

		        + ExercisesList: List<Exercises>
		        + Notes: List<Note<T>>
			}
			enum ExerciseType <<enum>> {
            		CARDIO
            		STRENGTH
            		MOBILITY
            		NONE
            	}
			WorkoutSession "1" ----l----> "0..*" Set: "                                                "

			AbstractExercise -> ExerciseType
	}

			WorkoutSession --r---> "Note<T>": "                                                                                                            "
	ActiveWorkoutSession -u-|> WorkoutSession
	CompletedWorkoutSession -u-|> WorkoutSession

	' NOTES
	!include note.puml

	class CompletedWorkoutSession <<POJO>> {
	}

	class ActiveWorkoutSession <<POJO>> {
	}

	together {

	}






@enduml
@startuml(id=SETS)

	class Set <<POJO>> {
		setNumber: Int
		setType: SetType
		exerciseId: UUID
		reps: Int
		weight: Double
		SetNotes: String?
	}

	enum SetType <<Enum>> {
		WARMUP
		NORMAL
        DROPSET
        FAILURE
	}


	Set --l-> SetType
@enduml
@startuml(id=Exercise)
skinparam linetype polyline
skinparam groupInheritance 3
	together {
		AbstractExercise <|---- UserExercise
        AbstractExercise <|---- SystemExercise


		abstract class AbstractExercise <<abstract>> {
			ExerciseId: UUID
		}
		class SystemExercise <<POJO>> {

		}
		class UserExercise  <<POJO>> {

		}
	}
@enduml