@startuml
		together {
			skinparam groupInheritance 2

			interface "Note<T>" {
				attachTargetType: <T>
				targetId: UUID
				NoteMessage: String?
			}
			class "ExerciseNote<Exercise>" implements "Note<T>"{

			}
			class "SessionNote<WorkoutSession>" implements "Note<T>" {

			}
		}
@enduml