@startuml
    'WorkoutSession
    '--> A completed or in-progress Workout.
    
    class WorkoutSession {
            -sessionId: Int
            -sourceRoutineId: UUID?
            -name: String
            -description: String
            ---
        }

    note top of WorkoutSession
        a workout Session is a <b>completed</b> Workout
    end note

    note right of WorkoutSession::sourceRoutineId
        Ref to a <b>WorkoutRoutine</b>, or <b>Null</b> if ad-hoc.
    end note

@enduml